name: dart_wmm
description: World Magnetic Model implementation in dart

publish_to: 'https://pub.dev/' 
repository: 'https://github.com/Thomas-Oz-Dunn/dart_wmm'

version: 0.0.1

environment:
  sdk: '^3.3.0'
dev_dependencies:
  test: ^1.25.5
